# Generated by Django 6.0 on 2026-01-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_delivery_fee_per_km_shop_free_delivery_above'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
