# Generated by Django 6.0 on 2026-01-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_product_image_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='banner_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='logo_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
